name: AN eKphrasIs

on:
  workflow_dispatch: # Manual trigger
  repository_dispatch: # API trigger
    types: [AN-eKphrasIs]
  schedule:
    - cron: '11 6 * * *' # MM HH * * * (UTC+0) -> +8h(UTC+8)

jobs:
  rAN_eKphrasIs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert

      - name: Run Auto-Web
        env:
          ANKI_ACCOUNT: ${{ secrets.ANKI_ACCOUNT }}
          ANKI_PASSWORD: ${{ secrets.ANKI_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          jupyter nbconvert --to notebook --execute --inplace an-ekphrasis.ipynb

      - name: Print execution log
        run: |
          jupyter nbconvert --to markdown an-ekphrasis.ipynb
          cat an-ekphrasis.md
